use_frameworks!

platform :ios, '13.0'

target 'XRightIconButton_Example' do
  pod 'XRightIconButton', :path => '../'

  target 'XRightIconButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
